application: insert_your_appname_here
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /(favicon.ico)
  static_files: static/img/\1
  upload: static/img/(.*)

- url: /admin/.*
  script: main.py
  login: admin
  
- url: .*
  script: main.py


